### ISSUE TITLE
use UTC time for "start"

### ISSUE THREAD

**Issue by ahsetiaki** [samber/slog-chi#10]
First of all, thanks for this middleware. Great work btw.

I think for ``start`` it should use UTC ``time.Now().UTC()`` instead of local ``time.Now()``. 

https://github.com/samber/slog-chi/blob/9af9b759189e53bb03767d97061923f6e85d14d6/middleware.go#L108

hdyt?

**Comment by samber** [comment]
thanks for the feedback

upgrade to 1.11.2
