### ISSUE TITLE
WithRequestID doesn't seem to do anything

### ISSUE THREAD

**Issue by tazimmerman** [samber/slog-chi#2]
Is the expectation that `WithRequestID: true` will use the request ID as set by chi's `middleware.RequestID`, or am I not following what it's mean to do?

Separately, thank you for this library, the multitude of other `slog`-related work. I was lucky enough to stumble upon your repos today and `slog-chi` is exactly what I was hoping to find.

**Comment by samber** [comment]
i just made a fix ;)

It uses the middleware.RequestID.

-> v1.3.2
