### ISSUE TITLE
Duplicate log messages on 4xx and 5xx statuses

### ISSUE THREAD

**Issue by tazimmerman** [samber/slog-chi#3]
I could be missing something, but it seems that responses with a 4xx or 5xx status are logged twice -- once in the check for the range of status codes, and once after that block regardless of status.

https://github.com/samber/slog-chi/blob/1124a4272621adffe954db40880cdd712f54f5fe/middleware.go#L194

Is that intentional?

**Comment by samber** [comment]
Definitely not :-(

I just made a fix. Thanks for the feedback.

-> v1.3.0
