### ISSUE TITLE
WithRequestID: true has no effect

### ISSUE THREAD

**Issue by tazimmerman** [samber/slog-chi#5]
It seems that `WithRequestID` was replaced by `WithRequestBody` at this line:

https://github.com/samber/slog-chi/blob/db1a0e8d530e5781134b049affd946622185bda1/middleware.go#L150

Unless this was intentional, it would be nice to keep the the request ID flag separate from the body flag.

**Comment by samber** [comment]
It was a mistake. Thanks for the report.

-> v1.5.1
